#ifndef EXPSUM_CHOLESKY_CAUCHY_HPP
#define EXPSUM_CHOLESKY_CAUCHY_HPP

#include <armadillo>
#include <cassert>

#include "expsum/numeric.hpp"

namespace expsum
{
//
// Rank-revealing Cholesky decomposition for a positive-definite quasi-Cauchy
// matrix.
//
// This class computes the Cholesky decomposition of ``$n \times n$``
// quasi-Cauchy matrix defined as
//
// ``` math
//  C_{ij}=\frac{a_{i}^{} b_{j}^{}}{x_{i}^{}+y_{i}^{}}.
// ```
//
template <typename T>
class cholesky_quasi_cauchy
{
public:
    using value_type = T;
    using real_type  = typename arma::get_pod_type<T>::result;
    using size_type  = arma::uword;

    using vector_type      = arma::Col<value_type>;
    using matrix_type      = arma::Mat<value_type>;
    using real_vector_type = arma::Col<real_type>;

private:
    size_type n_;
    arma::uvec ipiv_; // pivot order of rows
    vector_type work1_;
    vector_type work2_;

public:
    // Default constructor
    cholesky_quasi_cauchy() = default;
    // Constructor with allocating workspace
    explicit cholesky_quasi_cauchy(size_type n)
        : n_(n), ipiv_(n), work1_(n), work2_(n)
    {
    }
    // Default copy constructor
    cholesky_quasi_cauchy(const cholesky_quasi_cauchy&) = default;
    // Default move constructor
    cholesky_quasi_cauchy(cholesky_quasi_cauchy&&) = default;
    // Default destructor
    ~cholesky_quasi_cauchy() = default;
    // Copy assignment operator
    cholesky_quasi_cauchy& operator=(const cholesky_quasi_cauchy&) = default;
    // Move assignment operator
    cholesky_quasi_cauchy& operator=(cholesky_quasi_cauchy&&) = default;
    //
    // Compute Cholesky decomposition.
    //
    // @a vector of length ``$n$`` defining quasi-Cauchy matrix
    // @b vector of length ``$n$`` defining quasi-Cauchy matrix
    // @x vector of length ``$n$`` defining quasi-Cauchy matrix
    // @y vector of length ``$n$`` defining quasi-Cauchy matrix
    // @delta target size
    // @X matrix of dimention ``$n \times m$``, where ``$m$`` is the rank of
    //    Cauchy matrix ``$C$`` and is internaly determined.
    //    On exit, `X` holds Cholesky factor ``$X$`` which is a unit trianular
    //    matrix.
    // @d vector of length ``$m$``. On exit, `d` holds diagonal elements of
    //    Cholesky factor ``$D$``.
    //
    void run(vector_type& a, vector_type& b, vector_type& x, vector_type& y,
             real_type delta, matrix_type& X, real_vector_type& d)
    {
        const size_type n = a.size();
        resize(n);
        // Reorder vectors defining quasi-Cauchy matrix
        const size_type m = pivot_order(a, b, x, y, delta, ipiv_, work1_);

        // Compute Cholesky factor
        X.set_size(n, m);
        X.zeros();
        d.set_size(m);
        factorize(a, b, x, y, X, d, work1_, work2_);

        return;
    }
    //
    // Reserve memory for working space
    //
    void resize(size_type n)
    {
        n_ = n;
        ipiv_.set_size(n);
        work1_.set_size(n);
        work2_.set_size(n);
    }
    //
    // Apply permutation matrix generated by previous decomposition
    //
    template <typename Mat1, typename Mat2>
    void apply_row_permutation(const Mat1& src, Mat2& dest) const
    {
        using size_type = arma::uword;

        assert(src.n_rows == n_ && dest.n_rows == n_ &&
               src.n_cols == dest.n_cols);

        for (size_type j = 0; j < src.n_cols; ++j)
        {
            for (size_type i = 0; i < n_; ++i)
            {
                dest(ipiv_(i), j) = src(i, j);
            }
        }
    }
    //
    // Reconstruct matrix from Cholesky factor
    //
    // @X Cholesky factor computed by `cholesky_quasi_cauchy::run`.
    // @d Cholesky factor computed by `cholesky_quasi_cauchy::run`.
    //
    matrix_type reconstruct(const matrix_type& X, const real_vector_type& d)
    {
        matrix_type XD(X * arma::diagmat(d));
        matrix_type PXD(arma::size(XD));
        apply_row_permutation(XD, PXD);

        return matrix_type(PXD * PXD.t());
    }

private:
    //
    // Preconpute pivot order for the Cholesky factorization of $n \times n$
    // positive-definite Caunchy matrix $C_{ij}=a_{i}b_{j}/(x_{i}+y_{j}).$
    //
    static size_type pivot_order(vector_type& a, vector_type& b, vector_type& x,
                                 vector_type& y, real_type delta,
                                 arma::uvec& ipiv, vector_type& g);
    //
    // Compute Cholesky factors (`X` and diagonal part of `D`).
    //
    // The arrays `a,b,x,y` must be properly reordered by calling `pivot_order`
    // beforehand, so that the diagonal part of Cholesky factors appear in
    // decesnding order.
    //
    // @a vector of length ``$n$`` defining quasi-Cauchy matrix (reordered)
    // @b vector of length ``$n$`` defining quasi-Cauchy matrix (reordered)
    // @x vector of length ``$n$`` defining quasi-Cauchy matrix (reordered)
    // @y vector of length ``$n$`` defining quasi-Cauchy matrix (reordered)
    // @X Cholesky factor (lower triangular matrix)
    // @d diagonal elements of Cholesky factor ``$D$``
    // @alpha working space
    // @beta  working space
    //
    static void factorize(const vector_type& a, const vector_type& b,
                          const vector_type& x, const vector_type& y,
                          matrix_type& X, real_vector_type& d,
                          vector_type& alpha, vector_type& beta);

private:
};

//------------------------------------------------------------------------------
// Private member functions
//------------------------------------------------------------------------------
template <typename T>
typename cholesky_quasi_cauchy<T>::size_type
cholesky_quasi_cauchy<T>::pivot_order(vector_type& a, vector_type& b,
                                      vector_type& x, vector_type& y,
                                      real_type delta, arma::uvec& ipiv,
                                      vector_type& g)
{
    const size_type n = a.size();
    assert(b.size() == n);
    assert(x.size() == n);
    assert(y.size() == n);
    assert(ipiv.size() == n);
    assert(g.size() == n);
    //
    // Set cutoff for GECP termination
    //
    const auto eta = arma::Datum<real_type>::eps * delta * delta;
    //
    // Form vector g(i) = a(i) * b(i) / (x(i) + y(i))
    //
    g = (a % b) / (x + y);
    //
    // Initialize permutation matrix
    //
    ipiv = arma::linspace<arma::uvec>(0, n - 1, n);

    size_type m = 0;
    while (m < n)
    {
        //
        // Find m <= l < n such that |g(l)| = max_{m<=k<n}|g(k)|
        //
        const auto l    = arma::abs(g.tail(n - m)).index_max() + m;
        const auto gmax = std::abs(g(l));

        if (gmax < eta)
        {
            break;
        }

        if (l != m)
        {
            // Swap elements
            std::swap(g(l), g(m));
            std::swap(a(l), a(m));
            std::swap(b(l), b(m));
            std::swap(x(l), x(m));
            std::swap(y(l), y(m));
            // Swap _rows_ of permutation matrix
            std::swap(ipiv(l), ipiv(m));
        }

        // Update diagonal of Schur complement
        const auto xm = x(m);
        const auto ym = y(m);
        for (size_type k = m + 1; k < n; ++k)
        {
            g(k) *= (x(k) - xm) * (y(k) - ym) / ((x(k) + ym) * (y(k) + xm));
        }
        ++m;
    }
    //
    // Returns the truncation size
    //
    return m;
}

template <typename T>
void cholesky_quasi_cauchy<T>::factorize(const vector_type& a,
                                         const vector_type& b,
                                         const vector_type& x,
                                         const vector_type& y, matrix_type& X,
                                         real_vector_type& d,
                                         vector_type& alpha, vector_type& beta)
{
    const auto n = X.n_rows;
    const auto m = X.n_cols;
    assert(a.size() == n);
    assert(b.size() == n);
    assert(x.size() == n);
    assert(y.size() == n);
    assert(d.size() == m);
    assert(alpha.size() == n);
    assert(beta.size() == n);

    alpha = a;
    beta  = b;

    X.zeros();
    for (size_type l = 0; l < n; ++l)
    {
        X(l, 0) = alpha(l) * beta(0) / (x(l) + y(0));
    }

    for (size_type k = 1; k < m; ++k)
    {
        // Upgrade generators
        const auto xkm1 = x(k - 1);
        const auto ykm1 = y(k - 1);
        for (size_type l = k; l < n; ++l)
        {
            alpha(l) *= (x(l) - xkm1) / (x(l) + ykm1);
            beta(l) *= (y(l) - ykm1) / (y(l) + xkm1);
        }
        // Extract k-th column for Cholesky factors
        for (size_type l = k; l < n; ++l)
        {
            X(l, k) = alpha(l) * beta(k) / (x(l) + y(k));
        }
    }
    //
    // Scale strictly lower triangular part of G
    //   - diagonal part of G contains D**2
    //   - L = tril(G) * D^{-2} + I
    //
    for (size_type j = 0; j < m; ++j)
    {
        auto djj = X(j, j);
        d(j)     = std::sqrt(std::real(djj));
        X(j, j) = real_type(1);
        for (size_type i = j + 1; i < n; ++i)
        {
            X(i, j) /= djj;
        }
    }

    return;
}

} // namespace: expsum

#endif /* EXPSUM_CHOLESKY_CAUCHY_HPP */
